<div style="line-height:0.5">
<h1 style="color:#d6a042 "> Numpy useful methods and tricks 2 </h1>
</div>
<div style="line-height:1.5">
<div style="margin-top: -8px;">
<span style="display: inline-block;">
    <h3 style="color: lightblue; display: inline;">Keywords:</h3> functions + dot product + views
</span>
</div>
</div>

In [2]:
import random 
import numpy as np
from numpy.lib.stride_tricks import as_strided

In [15]:
arr0 = np.arange(0,50,4)
print(arr0)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48]


In [16]:
1/arr0[1:]

array([0.25      , 0.125     , 0.08333333, 0.0625    , 0.05      ,
       0.04166667, 0.03571429, 0.03125   , 0.02777778, 0.025     ,
       0.02272727, 0.02083333])

In [17]:
arr1 = np.linspace(1,10,20)
arr1

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [18]:
arr2=arr1.copy()
arr2[10:]=10  
arr2

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
       10.        , 10.        , 10.        , 10.        , 10.        ,
       10.        , 10.        , 10.        , 10.        , 10.        ])

In [19]:
## Check vals 
val=10
arr2==val

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [21]:
arr2[arr2<5]

array([1.        , 1.47368421, 1.94736842, 2.42105263, 2.89473684,
       3.36842105, 3.84210526, 4.31578947, 4.78947368])

In [33]:
# Reshape directly to 2dimension
arr3 = np.arange(0, 20).reshape(5,4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
#numpy.argsort(a, axis=-1, kind=None, order=None)
""" Return an array of indices of the same shape as a that index data along the given axis in sorted order. """
array_4 = np.array([100, 10, 50, 30])
array_4.argsort()

array([1, 3, 2, 0])

In [10]:
a = np.array(list('asdf'))
b = [3,2,0,1]
np.argsort(b)

array([2, 3, 1, 0])

In [11]:
a[np.argsort(b)]

array(['d', 'f', 's', 'a'], dtype='<U1')

In [20]:
x = np.array([[11,2,13],[0,5,2],[2,3,4]])
print(x)
print(x[:,1])
print(x[1:,0])
x[x[:,1].argsort()]

[[11  2 13]
 [ 0  5  2]
 [ 2  3  4]]
[2 5 3]
[0 2]


array([[11,  2, 13],
       [ 2,  3,  4],
       [ 0,  5,  2]])

<h2 style="color:#d6a042 "> Operations </h2>

In [ ]:
# Element-wise Addition
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x + y)
print()
print(np.add(x,y))
print()
print(x - y)
print()
print(np.subtract(x,y))

In [40]:
# Element-wise multiplication 
arr4 = np.arange(20, 40).reshape(5,4)
print(arr3 * arr4)
print()
print(np.multiply(arr3, arr4))

[[  0  21  44  69]
 [ 96 125 156 189]
 [224 261 300 341]
 [384 429 476 525]
 [576 629 684 741]]

[[  0  21  44  69]
 [ 96 125 156 189]
 [224 261 300 341]
 [384 429 476 525]
 [576 629 684 741]]


In [39]:
# Element-wise division
print(arr3/arr4)
print()
print(np.divide(arr3, arr4))
print()
print(np.sqrt(arr3))

[[0.         0.04761905 0.09090909 0.13043478]
 [0.16666667 0.2        0.23076923 0.25925926]
 [0.28571429 0.31034483 0.33333333 0.35483871]
 [0.375      0.39393939 0.41176471 0.42857143]
 [0.44444444 0.45945946 0.47368421 0.48717949]]

[[0.         0.04761905 0.09090909 0.13043478]
 [0.16666667 0.2        0.23076923 0.25925926]
 [0.28571429 0.31034483 0.33333333 0.35483871]
 [0.375      0.39393939 0.41176471 0.42857143]
 [0.44444444 0.45945946 0.47368421 0.48717949]]

[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]
 [3.46410162 3.60555128 3.74165739 3.87298335]
 [4.         4.12310563 4.24264069 4.35889894]]


In [53]:
x = np.random.randint(0, 100, size=(15, 5))
y = np.random.randint(0, 100, size=(5, 15))

print(x)
print()
print(y)

[[99 93 53 60 89]
 [36  3 52 87 35]
 [52  1 70 95  5]
 [33 87 17 90 60]
 [94 64 53 76 12]
 [53 66 96 12 49]
 [38 33 82 52  7]
 [47 36 29 78 29]
 [27 84 72 78 16]
 [ 3  8 62 99 56]
 [93 71 88 56 96]
 [ 8 24 56 46 38]
 [ 6 89 72 80 97]
 [ 5 35 38  1 30]
 [91 84  4 93 37]]

[[60 83 97 43 11 37 15 74 44 54 64 99 51 27 77]
 [87 83 89 94 36 22 20  7 97 77 23 27 98 37 83]
 [84 45 30  0 63 37 82  7 39 16 92 91 13  5 86]
 [ 9 71 44 97 50 43 73  8 60  5 52 27 85 96 99]
 [45  7 15 50 61 22 98 45  6  3  5  4 41 47 94]]


In [54]:
# Matrix Multiplication (Dot Product)
print(x.dot(y))
print()
print(np.dot(x,y))

[[23028 23204 23445 23269 16205 12208 20793 12833 19578 13922 16916 19111
  23601 16322 34206]
 [ 9147 11999  9672 12019 10265  7833 14645  5320  9333  3547 11856 10866
  11636 11340 19396]
 [10167 14329 11488 11795 10073  8731 13965  5330 10845  4495 14756 14130
  11940 11146 19982]
 [14487 17535 16314 21327 12726  8954 16079  6590 16314  9383 10657  9833
  20540 15655 25774]
 [16884 20979 19928 18030 11209 10379 13760  8923 17043 11268 16376 17957
  18707 13031 25760]
 [19299 15392 15158 12097 12596  8559 15665  7357 13492  9687 14611 16285
  13448  7808 23609]
 [12822 13324 11476 10130  9799  7556 12436  4348 11233  6186 13474 13547
  10945  7978 18523]
 [10395 13935 12500 14421  9309  7596 12339  5862 11545  6251 10705 10486
  14121 11597 19549]
 [16398 18103 15927 17423 12733  9217 15251  4434 16920  9516 14420 13663
  17831 12437 24469]
 [ 9495 11124  8059 13284 12593  8070 18004  4024  9602  2433 11508  9052
  12454 12823 21292]
 [23973 22220 21884 20905 17779 12779 23527 12763 

In [4]:
# Dot product
a = np.array([[1,2,3,4], [1,2,3,4]])
b = np.array([[1,2,3,4], [1,2,3,4], [1,2,3,4], [1,2,3,4]])
print(a.dot(b))

[[10 20 30 40]
 [10 20 30 40]]


In [58]:
""" Summations """
# All number sum
print("--> Sum all")
print(np.sum(x)) 
# Column-wise sum
print("--> Sum column")
print(np.sum(x,axis=0))  
# Row-wise sum
print("--> Sum row")
print(np.sum(x,axis=1))  

--> Sum all
3966
--> Sum column
[ 685  778  844 1003  656]
--> Sum row
[394 213 223 287 299 276 212 219 277 228 404 172 344 109 309]


In [5]:
# Min in columns, Min in rows
np.min(a,axis=0), np.min(a,axis=1)

(array([1, 2, 3, 4]), array([1, 1]))

In [63]:
### Mean
print("Mean of x is: {}".format(np.mean(x)))
print("Mean of x (rows) is: {}".format(np.mean(x, axis=0)))
print("Mean of x (columns) is: {}".format(np.mean(x, axis=1)))

Mean of x is: 52.88
Mean of x (rows) is: [45.66666667 51.86666667 56.26666667 66.86666667 43.73333333]
Mean of x (columns) is: [78.8 42.6 44.6 57.4 59.8 55.2 42.4 43.8 55.4 45.6 80.8 34.4 68.8 21.8
 61.8]


In [67]:
# Median
tmp_list = [random.randint(0, 100) for _ in range(30)]
arr5 = np.array(tmp_list)
print(np.median(arr5))

41.5


In [68]:
# Weights 
w = [random.randint(0, 100) for _ in range(30)]

np.average(arr5, weights=w)

40.05289139633286

In [70]:
# Variance 
dev= np.std(arr5)
dev

27.990097455270778

In [71]:
np.random.randint(0, 100, 8).reshape(4,2)

array([[30, 37],
       [32, 17],
       [27,  1],
       [96, 46]])

In [72]:
np.random.random_sample((1, 5))

array([[0.6941225 , 0.14893967, 0.75306765, 0.78099498, 0.5657737 ]])

In [73]:
new_a = np.array([1,2,3,4,5,6,7,8,9,2,3,4,5,6,7,8,1,2,3,7,8,9])
new_a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 7, 8, 9])

In [74]:
new_a.argsort() 
new_a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 7, 8, 9])

<h2 style="color:#d6a042 "> Functions </h2>

In [5]:
""" Trigonometric functions """
theta = np.linspace(0, np.pi, 5)
print(theta)
sin = np.sin(theta)
cos = np.cos(theta)
tan = np.tan(theta)

print(f"sin => {sin}")
print(f"cos => {cos}")
print(f"tan => {tan}")

[0.         0.78539816 1.57079633 2.35619449 3.14159265]
sin => [0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
cos => [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]
tan => [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.00000000e+00
 -1.22464680e-16]


In [6]:
""" Exponential functions """
x = np.array([-1, 0, 1])
print(f"arcsin = {np.arcsin(x)}")
print(f"arccos = {np.arccos(x)}")
print(f"arctan = {np.arctan(x)}")

arcsin = [-1.57079633  0.          1.57079633]
arccos = [3.14159265 1.57079633 0.        ]
arctan = [-0.78539816  0.          0.78539816]


In [7]:
""" Inverse trigonometric function """
x = np.arange(1, 8)
print(f"function e^x => = {np.exp(x)}")
print(f"function 2^x => = {np.exp2(x)}")
print(f"function 3^x => = {np.power(3, x)}")

e^x => = [   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591
  403.42879349 1096.63315843]
2^x => = [  2.   4.   8.  16.  32.  64. 128.]
3^x => = [   3    9   27   81  243  729 2187]


In [8]:
""" Logarithms """
x = np.random.randint(1, 5, size=4)
print(f"ln = {np.log(x)}")
print(f"log2 = {np.log2(x)}")
print(f"log10 = {np.log10(x)}")

ln = [1.38629436 0.69314718 0.69314718 1.38629436]
log2 = [2. 1. 1. 2.]
log10 = [0.60205999 0.30103    0.30103    0.60205999]


In [12]:
np.random.seed(0)
marks = np.random.randint(20, 80, size=(4,6))
mini = marks.min(axis=0)
maxi = marks.max(axis=0)
sumi = marks.sum(axis=1)

print(marks)
print()
print(f" mini = {mini}")
print(f" maxi = {maxi}")
print(f" sumi = {sumi}")

[[64 67 73 20 23 79]
 [23 59 29 39 41 70]
 [56 43 26 44 44 32]
 [78 21 58 59 43 66]]

 mini = [23 21 26 20 23 32]
 maxi = [78 67 73 59 44 79]
 sumi = [326 261 245 325]


In [22]:
a = np.arange(3)
a

array([0, 1, 2])

In [23]:
b = np.ones((3,1)) 
b

array([[1.],
       [1.],
       [1.]])

In [24]:
a + b 

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

<h3 style="color:#d6a042 "> => Masking </h3>

In [34]:
np.random.seed(0)
x = np.random.randint(150, size=(3,4))
print(x)
print()
print([x<100])
print()
print(x[x<100])
print()

[[ 47 117  67 103]
 [  9  21  36  87]
 [ 70  88 140  58]]

[array([[ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]])]

[47 67  9 21 36 87 70 88 58]



<h2 style="color:#d6a042 "> Fancy indexing </h2>

In [36]:
x = np.random.randint(100, size=10)
print(x)
print()
print(x[[2,5,9]])

[99 88 49 29 19 19 14 39 32 65]

[49 19 65]


In [46]:
# Avoid repeatition of numbers, 
#x = np.random.randint(100, size=(4, 7), replace=False) 
x = np.random.choice(100, size=(4, 7), replace=False) 

print(x)
# Index must be in bounds => <4 for x and <7 for y
row = [1, 3, 0]
col = [4, 6, 5]
print()
print(x[row, col])
print()
print(x[2,[1, 3, 6]])

[[87 12 14 81 36 50 73]
 [ 6 64 58 34 55 62 59]
 [15 95 42 52 22 17 77]
 [49 16 92 30 57 66  0]]

[55  0 50]

[95 52 77]


In [47]:
# Return the indices that would sort an array in acending order
np.argsort(x)

array([[1, 2, 4, 5, 6, 3, 0],
       [0, 3, 4, 2, 6, 5, 1],
       [0, 5, 4, 2, 3, 6, 1],
       [6, 1, 3, 0, 4, 5, 2]])

<h2 style="color:#d6a042 "> Reshape </h2>

The "strides" attribute contains for each dimension,the number of bytes (not array indexes)

In [48]:
a = np.random.rand(20_000, 10_000)
print(f'{a.strides=}')  # (80000, 8)
b = a.reshape(40_000, 5_000)
print(f'{b.strides=}')  # (40000, 8)
c = a.reshape(20_000, 5_000, 2)
print(f'{c.strides=}')  # (80000, 16, 8)

a.strides=(80000, 8)
b.strides=(40000, 8)
c.strides=(80000, 16, 8)


In [51]:
def transpose(a):
    return as_strided(a, shape=a.shape[::-1], strides=a.strides[::-1])

# Test the function on a small matrix
a = np.array([[1, 2, 3], [4, 5, 6]])

print('Before transpose:')
print(a)
print('After transpose:')
print(transpose(a))

Before transpose:
[[1 2 3]
 [4 5 6]]
After transpose:
[[1 4]
 [2 5]
 [3 6]]


<h2 style="color:#d6a042 "> View </h2>
<div style="margin-top: -34px;">

Key properties of views created by these methods:

+ No data copying, they reference the source array
+ Changes are reflected in both view and source
+ Faster than copies but take up similar memory
</div>

In [54]:
""" Base attribute refers to the original array that a view was created from. """
a = np.zeros((5, 5))
print(a.base)
# Create a view by slicing
b = a[:2, :2]
print(b.base.shape)

None
(5, 5)


In [53]:
print(a.__array_interface__['data'])
print(b.__array_interface__['data'])

(40524752, False)
(40524752, False)


In [55]:
# View of rows 0 and 1
b = a[[0,1], :] 
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
# View with specific indices
indices = [0,2,4]  
b = a[indices] 

In [ ]:
# View with every second element
b = a[::2] 

In [ ]:
# View with mask  
mask = [True, False, True]
b = a[mask]

In [ ]:
# View returned from numpy
b = np.sqrt(a)

In [ ]:
# View from a transposed 
b = a.T

<h2 style="color:#d6a042 "> Data Type Hierarchy</h2>

In [57]:
# Parent classes of a specific data type
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [63]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
print(np.issubdtype(ints.dtype, np.integer))
print(np.issubdtype(floats.dtype, np.floating))
print(np.issubdtype(ints.dtype, np.number))
print(np.issubdtype(ints.dtype, np.floating))

True
True
True
False


<h2 style="color:#d6a042 "> Reshaping </h2>

In [65]:
arr = np.arange(8)
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [66]:
# Double reshaping
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
other_arr = np.ones((3, 5))
other_arr, other_arr.shape

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 (3, 5))

In [73]:
oa = other_arr.ravel()
oa

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [74]:
fla = arr.flatten()
fla

array([0, 1, 2, 3, 4, 5, 6, 7])

<h2 style="color:#d6a042 "> Repeat elements </h2>

In [75]:
repe = arr.repeat(3)
repe

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7])

In [78]:
rape2 = arr.repeat(2, axis=0)
rape2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7])

In [83]:
""" Broadcast the repeat arguments to the array length Repeat each elements of the list according to the times indicated by another list. """

# AxisError: axis 1 (second dimension) is out of bounds for array of dimension 1
#arr.repeat([2, 3], axis=1)
# Error: Incompatible shapes: arr has length 8, the repeat list [2,3] only has length 2
#arr.repeat([2, 3], axis=0)
repe = [2, 3, 1, 2, 1, 2, 3, 1] 
arr.repeat(repe, axis=0)

array([0, 0, 1, 1, 1, 2, 3, 3, 4, 5, 5, 6, 6, 6, 7])