<div style="line-height:0.5">
<font size="6" style="color:moccasin"> Numpy useful methods and tricks 1 </font>
</div>
<div style="margin-top: 10px;">
<span style="display: inline-block;">
    <h3 style="color: lightblue; display: inline;">Keywords:</h3>
    numpy arrays + np.prod + broadcasting + random arrays + print tables + math + slicing
</span>
</div>
</div> 

In [1]:
import random
import scipy as sc
import numpy as np
import pandas as pd
from tabulate import tabulate

In [2]:
arr1 = np.array([1,2,3], dtype='int16')
arr2 = np.array((1,2,3,4,5,6))
arr3 = np.array([[1],[2],[3]])
arr4 = np.mat([[1],[2],[3]])

my_df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})
arr5 = my_df.values
print(arr5)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
l = [1,2,3]
npl = np.asarray(l)
npl1 = np.asanyarray(l)
type(npl1)

numpy.ndarray

<h3 style="color:moccasin "> => Copy </h3>

In [4]:
art1 = [4,5,6]
art2 = np.array(art1, copy=True)

art3 = art1

print(art2)
print(art3)
print()

art2[0] = 1 #do not modify the original one
art3[0] = 2 #modify the original one

print(art1)
print(art2)
print(art3)


[4 5 6]
[4, 5, 6]

[2, 5, 6]
[1 5 6]
[2, 5, 6]


In [5]:
my_generator = (x**2 for x in range(5)) # generator of numbers
my_array = np.fromiter(my_generator, dtype=int) # np.int is deprecated
print(my_array)

[ 0  1  4  9 16]


In [6]:
my_array0 = np.zeros((2, 3), dtype=float)
my_array1 = np.ones((2, 3), dtype=int)
my_array2 = np.full((2, 3), 3.3, dtype=float)

my_array3 = np.eye(5)           # identity
arreye = np.eye(4,k=1)          # identity
arreye1 = np.eye(4,k=-1)        # identity translated
my_array4 = np.identity(4)

arrass = np.empty(2)            # 2 random float values
arrass1 = np.empty((2,3))

print(f"my_array0 is ==>\n {my_array0}")
print(f"my_array1 is ==>\n {my_array1}")
print(f"my_array2 is ==>\n {my_array2}")
print(f"my_array3 is ==>\n {my_array3}")
print(f"arreye is ==>\n {arreye}")
print(f"arreye1 is ==>\n {arreye1}")
print(f"my_array4 is ==>\n {my_array4}")
print(f"arrass is ==>\n {arrass}")
print(f"arrass1 is ==>\n {arrass}")

""" # (start stop step) """
my_array40 = np.linspace(0, 1, 5)               # between 0 and 1 
my_array400 = np.linspace(0, 10, 5)             # between 0 and 10 
my_array41 = np.linspace(0, 20, 1)              # between 0 and 20
my_array42 = np.linspace(0, 20, 2)               
my_array43 = np.linspace(0, 20, 3)              
my_array44 = np.linspace(0, 20, 4)              
my_array45 = np.linspace(0, 20, 5, dtype=int)   
my_array5 = np.arange(1, 10, 1)                   

print(my_array40)
print(my_array400)
print()
print(my_array41)
print(my_array42)
print(my_array43)
print(my_array44)
print(my_array45)

aa1 = np.full_like((2, 28), 99)
aa2 = np.full_like((1, 1), 99)
aa3 = np.full_like(aa2, 11)

print()
print()
print()
print(aa1)
print(aa2)
print(aa3)

my_array0 is ==>
 [[0. 0. 0.]
 [0. 0. 0.]]
my_array1 is ==>
 [[1 1 1]
 [1 1 1]]
my_array2 is ==>
 [[3.3 3.3 3.3]
 [3.3 3.3 3.3]]
my_array3 is ==>
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
arreye is ==>
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
arreye1 is ==>
 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
my_array4 is ==>
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
arrass is ==>
 [-2.00000000e+000  6.95306786e-310]
arrass1 is ==>
 [-2.00000000e+000  6.95306786e-310]
[0.   0.25 0.5  0.75 1.  ]
[ 0.   2.5  5.   7.5 10. ]

[0.]
[ 0. 20.]
[ 0. 10. 20.]
[ 0.          6.66666667 13.33333333 20.        ]
[ 0  5 10 15 20]



[99 99]
[99 99]
[11 11]


In [7]:
another_array1 = np.random.rand(1,2,3)
another_array2 = np.array([[1,2,3]])
another_array3 = np.repeat(another_array2, 2) 
another_array4 = np.repeat(another_array2, 2, axis=0)

print()
print(another_array1)
print()
print()
print(another_array2)
print()
print(another_array3)
print()
print(another_array4)


[[[0.63386275 0.12800382 0.89587525]
  [0.07910922 0.30129955 0.75412032]]]


[[1 2 3]]

[1 1 2 2 3 3]

[[1 2 3]
 [1 2 3]]


<h3 style="color:moccasin "> => Recap: </h3>
<div style="margin-top: -8px;">
Ndim: <br>    
Number of dimensions (or axes) of the array => 2 if 2-dimensional array.       

Shape:      
The number of elements (size) in each dimension as a tuple.        
Dimension is the number of indices or subscripts, that we require in order to specify an individual element of an array.       
=> if dim=6 shape can be (1,2,3,4,5,6).            
=> arr4.shape is (3, 1).     

Dtype: <br>
Data type of the elements in the array (int64).      

Size:<br>
Total number of elements in the array.      
=> arr5 has 3 rows and 3 column, the total number of elements is 3*3 = 9.       

Itemsize: <br>
Size (in bytes) of each element in the array. For an int64 data type, each element takes up 8 bytes.      

Total_size: <br>     
arr4.size * arr4.itemsize: 
The total number of bytes based on the number of elements and the size of each element.       
For arr4, the calculation is 3 * 8 = 24       

Nbytes: <br>
Total number of bytes used by the array data.    
=> arr4 has 3 elements and each element is 8 bytes, the total size is 3 * 8 = 24 bytes        
=> arr5.nbytes = arr5.size * arr5.itemsize = 9 * 8 = 72 bytes  
</div>

In [33]:
""" Basics """
print(arr1)
print()
print("arr1.ndim", arr1.ndim)
print("arr1.shape", arr1.shape)
print("arr1.data type", arr1.dtype)
print("arr1. size", arr1.size)
print("arr1.item size", arr1.itemsize) # dtype / 8 bit
print("arr1.total size", arr1.size*arr1.itemsize)
print("arr1.nbytes", arr1.nbytes)
print()
print()
print(arr2)
print()
print("arr2.ndim", arr2.ndim)
print("arr2.shape", arr2.shape)
print("arr2.data type", arr2.dtype)
print("arr2. size", arr2.size)
print("arr2.item size", arr2.itemsize)
print("arr2.total size", arr1.size*arr2.itemsize)
print("arr2.nbytes", arr2.nbytes)
print()
print()
print(arr3)
print()
print("arr3.ndim", arr3.ndim)
print("arr3.shape", arr3.shape)
print("arr3.data type", arr3.dtype)
print("arr3. size", arr3.size)
print("arr3.item size", arr3.itemsize)
print("arr3.total size", arr1.size*arr3.itemsize)
print("arr3.nbytes", arr3.nbytes)
print()
print()
print(arr4)
print()
print("arr4.ndim", arr4.ndim)
print("arr4.shape", arr4.shape)
print("arr4.data type", arr4.dtype)
print("arr4. size", arr4.size)
print("arr4.item size", arr4.itemsize)
print("arr4.total size", arr1.size*arr4.itemsize)
print("arr4.nbytes", arr4.nbytes)
print()
print()
print(arr5)
print()
print("arr5.ndim", arr5.ndim)
print("arr5.shape", arr5.shape)
print("arr5.data type", arr5.dtype)
print("arr5. size", arr5.size)
print("arr5.item size", arr5.itemsize)
print("arr5.total size", arr1.size*arr5.itemsize)
print("arr5.nbytes", arr5.nbytes)

[1 2 3]

arr1.ndim 1
arr1.shape (3,)
arr1.data type int16
arr1. size 3
arr1.item size 2
arr1.total size 6
arr1.nbytes 6


[1 2 3 4 5 6]

arr2.ndim 1
arr2.shape (6,)
arr2.data type int64
arr2. size 6
arr2.item size 8
arr2.total size 24
arr2.nbytes 48


[[1]
 [2]
 [3]]

arr3.ndim 2
arr3.shape (3, 1)
arr3.data type int64
arr3. size 3
arr3.item size 8
arr3.total size 24
arr3.nbytes 24


[[1]
 [2]
 [3]]

arr4.ndim 2
arr4.shape (3, 1)
arr4.data type int64
arr4. size 3
arr4.item size 8
arr4.total size 24
arr4.nbytes 24


[[1 4 7]
 [2 5 8]
 [3 6 9]]

arr5.ndim 2
arr5.shape (3, 3)
arr5.data type int64
arr5. size 9
arr5.item size 8
arr5.total size 24
arr5.nbytes 72


720

In [24]:
# 3-dimensional array
array_new1 = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])

print("Number of dimensions:", array_new1.ndim)
print("Shape:", array_new1.shape)
print("Data type:", array_new1.dtype)
print("Total number of elements:", array_new1.size)
print("Size of each element:", array_new1.itemsize, "bytes")
print("Total size in bytes:", array_new1.nbytes, "bytes")

Number of dimensions: 2
Shape: (3, 3)
Data type: int64
Total number of elements: 9
Size of each element: 8 bytes
Total size in bytes: 72 bytes


In [25]:
# 3-dimensional array
array_new2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

print("Number of dimensions:", array_new2.ndim)
print("Shape:", array_new2.shape)
print("Data type:", array_new2.dtype)
print("Total number of elements:", array_new2.size)
print("Size of each element:", array_new2.itemsize, "bytes")
print("Total size in bytes:", array_new2.nbytes, "bytes")

Number of dimensions: 3
Shape: (3, 2, 2)
Data type: int64
Total number of elements: 12
Size of each element: 8 bytes
Total size in bytes: 96 bytes


In [36]:
# 4-dimensional array
array_new3 = np.random.randint(0, 255, size=(4, 3, 5, 6))

print("Number of dimensions:", array_new3.ndim)
print("Shape:", array_new3.shape)
print("Data type:", array_new3.dtype)
print("Total number of elements:", array_new3.size)
print("Size of each element:", array_new3.itemsize, "bytes")
print("Total size in bytes:", array_new3.nbytes, "bytes")

Number of dimensions: 4
Shape: (4, 3, 5, 6)
Data type: int64
Total number of elements: 360
Size of each element: 8 bytes
Total size in bytes: 2880 bytes


In [40]:
# 5-dimensional array
array_new4 = np.random.rand(2, 3, 4, 5, 6)

print("Number of dimensions:", array_new4.ndim)
print("Shape:", array_new4.shape)
print("Data type:", array_new4.dtype)
print("Total number of elements:", array_new4.size)
print("Size of each element:", array_new4.itemsize, "bytes")
print("Total size in bytes:", array_new4.nbytes, "bytes")

Number of dimensions: 5
Shape: (2, 3, 4, 5, 6)
Data type: float64
Total number of elements: 720
Size of each element: 8 bytes
Total size in bytes: 5760 bytes


In [41]:
""" Product between all elements with np.prod().

In last case the value 9.427113e-318 (can variate) is extremely close to zero, 
but it's not exactly zero due to the limitations of floating-point representation in computers. 
This result is expected when calculating the product of a random array of floating-point values, 
as the product of many small numbers can lead to an underflow situation where the value becomes very close to zero.
"""
pro1 = np.prod(arr1)
pro2 = np.prod(arr2)
pro3 = np.prod(arr3)
pro4 = np.prod(arr4)
pro5 = np.prod(arr5)
pro6 = np.prod(array_new1)
pro7 = np.prod(array_new2)
pro8 = np.prod(array_new3)
pro9 = np.prod(array_new4)

print(f"pro1 is ==> {pro1}")
print(f"pro2 is ==> {pro2}")
print(f"pro3 is ==> {pro3}")
print(f"pro4 is ==> {pro4}")
print(f"pro5 is ==> {pro5}")
print(f"pro6 is ==> {pro6}")
print(f"pro7 is ==> {pro7}")
print(f"pro8 is ==> {pro8}")
print(f"pro9 is ==> {pro9}")

pro1 is ==> 6
pro2 is ==> 720
pro3 is ==> 6
pro4 is ==> 6
pro5 is ==> 362880
pro6 is ==> 362880
pro7 is ==> 479001600
pro8 is ==> 0
pro9 is ==> 9.427113e-318


<h3 style="color:moccasin "> => Recap: Broadcasting </h3>
<div style="margin-top: -9px;">

Broadcasting is a powerful feature that allows NumPy to perform element-wise operations on arrays with different shapes,<br>
making them compatible when certain conditions are met.<br>
Adding extra brackets essentially means to introduce new dimensions with size 1.<br>
These additional dimensions are automatically broadcasted to match the shape of array_new4 when performing element-wise operations. <br>
It is like performing the operation array_new4 + [[0], [0], [0], [0]] <br>
</div>

In [61]:
array_new4[[[[[[[[[[0],[0],[0],[0]]]]]]]]]]

array([[[[[[[[[[[[[0.32403043, 0.94088073, 0.48993547,
                   0.71169998, 0.04365568, 0.95617099],
                  [0.65769962, 0.43981125, 0.62078312,
                   0.32054876, 0.60681792, 0.53822827],
                  [0.51917258, 0.31027175, 0.92240294,
                   0.17278232, 0.82827799, 0.38372197],
                  [0.80298316, 0.57963876, 0.36289998,
                   0.50834025, 0.11463096, 0.94912215],
                  [0.82522881, 0.12218431, 0.6926988 ,
                   0.09480468, 0.08520313, 0.60264788]],

                 [[0.61266701, 0.1023234 , 0.79580317,
                   0.35322031, 0.89450577, 0.40433949],
                  [0.59540098, 0.19000401, 0.0354653 ,
                   0.69634077, 0.58874019, 0.68863927],
                  [0.59537924, 0.0609509 , 0.26981044,
                   0.70140912, 0.38590783, 0.93573765],
                  [0.33681876, 0.32479823, 0.65536578,
                   0.23953381, 0.29462983, 0.10274624],

<h3 style="color:moccasin "> => Create random arrays </h3>

In [9]:
random_a = np.random.randint(1, 101, size=15)
differe = np.diff(random_a)
print(random_a)
differe

[53 33 38 75 74  4  7 78 21 96 67 66 13 25 81]


array([-20,   5,  37,  -1, -70,   3,  71, -57,  75, -29,  -1, -53,  12,
        56])

In [10]:
xy = np.random.random(10)
zw = np.random.random(10)
print(f"xy is\n {xy}")
print(f"zw is\n {zw}")
con = np.concatenate([xy, zw])
#or
con1 = np.concatenate((xy, zw))
print()
print(con)
print()
print(con1)

xy is
 [0.62100534 0.9803088  0.12144996 0.86235891 0.32096937 0.32484648
 0.48486467 0.0742028  0.74942748 0.90134449]
zw is
 [0.60265174 0.79930137 0.62372752 0.35993659 0.6108105  0.4554464
 0.40436844 0.27504787 0.2829261  0.42089607]

[0.62100534 0.9803088  0.12144996 0.86235891 0.32096937 0.32484648
 0.48486467 0.0742028  0.74942748 0.90134449 0.60265174 0.79930137
 0.62372752 0.35993659 0.6108105  0.4554464  0.40436844 0.27504787
 0.2829261  0.42089607]

[0.62100534 0.9803088  0.12144996 0.86235891 0.32096937 0.32484648
 0.48486467 0.0742028  0.74942748 0.90134449 0.60265174 0.79930137
 0.62372752 0.35993659 0.6108105  0.4554464  0.40436844 0.27504787
 0.2829261  0.42089607]


In [11]:
arr = np.random.randint(1, 7, 10) #(min,max,leng)
arrun = np.unique(arr)
print(arr)
print(arrun)
print(np)

#The numpy.random.shuffle function shuffles the elements of an array in-place, 
# so it modifies the original array and does not return any value
shu = np.copy(arr)
np.random.shuffle(shu)
print(type(shu))
print(shu)
print(list(shu))

[3 1 3 2 3 1 2 5 1 6]
[1 2 3 5 6]
<module 'numpy' from '/home/notto4/anaconda3/envs/MLearning/lib/python3.10/site-packages/numpy/__init__.py'>
<class 'numpy.ndarray'>
[1 6 1 2 1 3 5 3 2 3]
[1, 6, 1, 2, 1, 3, 5, 3, 2, 3]


In [12]:
cli = np.clip(xy, 0.2813133, 0.74333962)
cli

array([0.62100534, 0.74333962, 0.2813133 , 0.74333962, 0.32096937,
       0.32484648, 0.48486467, 0.2813133 , 0.74333962, 0.74333962])

In [13]:
ti = np.tile(np.arange(3),5)
rep = np.repeat(np.arange(3),5)
print(f"repeat is => {rep}" )
print(f"tieat is => {ti}" )
print(f"only some in which contion is satisfied (elem > 0.1).... {np.where(ti > 0.1)}") #return indexes of positions
print()
con1 = np.concatenate((ti, rep))
con1 = con.reshape(2,10)
print(con1)
ra = np.ravel(con1) # flatten
ra

repeat is => [0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]
tieat is => [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
only some in which contion is satisfied (elem > 0.1).... (array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14]),)

[[0.62100534 0.9803088  0.12144996 0.86235891 0.32096937 0.32484648
  0.48486467 0.0742028  0.74942748 0.90134449]
 [0.60265174 0.79930137 0.62372752 0.35993659 0.6108105  0.4554464
  0.40436844 0.27504787 0.2829261  0.42089607]]


array([0.62100534, 0.9803088 , 0.12144996, 0.86235891, 0.32096937,
       0.32484648, 0.48486467, 0.0742028 , 0.74942748, 0.90134449,
       0.60265174, 0.79930137, 0.62372752, 0.35993659, 0.6108105 ,
       0.4554464 , 0.40436844, 0.27504787, 0.2829261 , 0.42089607])

In [14]:
st = "hello_word".encode()
len(st)
ast = np.frombuffer(st, dtype='S1', count=5, offset=0)
print(ast)
decoded_ast = np.char.decode(ast, 'utf-8')
print(decoded_ast)
ast1 = np.frombuffer(st, dtype='S1', offset=2)
print(ast1)

[b'h' b'e' b'l' b'l' b'o']
['h' 'e' 'l' 'l' 'o']
[b'l' b'l' b'o' b'_' b'w' b'o' b'r' b'd']


<h3 style="color:moccasin "> => fancy print</h3>

In [15]:
#fancy print 1
m = np.array([[1, 2, 3], [4, 5, 6]])
headers = ["col 1", "col 2", "col 3"]
table = tabulate(m, headers, tablefmt="fancy_grid")
print(table)
#fancy print 2
for c1, c2, c3 in m:  
    print ("%2f | %8e | %s" % (c1, c2, c3))

╒═════════╤═════════╤═════════╕
│   col 1 │   col 2 │   col 3 │
╞═════════╪═════════╪═════════╡
│       1 │       2 │       3 │
├─────────┼─────────┼─────────┤
│       4 │       5 │       6 │
╘═════════╧═════════╧═════════╛
1.000000 | 2.000000e+00 | 3
4.000000 | 5.000000e+00 | 6


<h2 style="color:moccasin "> <u> Maths </u> </h2>

In [16]:
########################################################## copy
aa = np.array([1,2,3,4])
bb = aa.copy()
########################################################## maths
print()
print(aa + 2)
print(aa % 2)
print(aa - 2)
print(aa ** 2)
print(np.sin(aa))
print(aa+bb)
########################################################## linear algebra
ar1 = np.ones((2,3))
ar2 = np.full((3,2),2)
ar3 = np.matmul(ar1,ar2)
print()
print(ar3)
########################################################## statistics
stats = np.array([[1,2,3],[4,5,6]])
min_stats = np.min(stats) #total > 1 
min_stats0 = np.min(stats, axis=0) #for 1dim [1,2,3]
min_stats1 = np.min(stats, axis=1) #for both 2dim [1,4]]
print()
print('#')
print(min_stats)
print('#0')
print(min_stats0)
print('#1')
print(min_stats1)


[3 4 5 6]
[1 0 1 0]
[-1  0  1  2]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[2 4 6 8]

[[6. 6.]
 [6. 6.]]

#
1
#0
[1 2 3]
#1
[1 4]


<h3 style="color:moccasin "> => operation with matrices </h3>

In [17]:
matrix = np.array([[1, 1, 1], [1, 1, 10], [1, 1, 15]]) 
# Return matrix rank 
print(np.linalg.matrix_rank(matrix))
print(np.linalg.det(matrix))
print(np.diagonal(matrix))
print(matrix.trace())

# Finding Eigenvalues and Eigenvectors 
# 
matrix1 = np.array([[1, -1, 3], [1, 1, 6], [3, 8, 9]]) 
# Calculate eigenvalues and eigenvectors 
eigenvalues, eigenvectors = np.linalg.eig(matrix) 
print(f" eigenvalues, eigenvectors are =>\n {eigenvalues}, {eigenvectors}")
print()
print(f" eigenvalues, eigenvectors are =>\n {eigenvalues, eigenvectors}")


2
0.0
[ 1  1 15]
17
 eigenvalues, eigenvectors are =>
 [1.57972598e+01 1.20274024e+00 4.17207245e-17], [[ 9.35154454e-02  9.54818342e-01  7.07106781e-01]
 [ 5.61805577e-01  2.83317939e-01 -7.07106781e-01]
 [ 8.21966761e-01 -8.97378394e-02 -4.99981379e-17]]

 eigenvalues, eigenvectors are =>
 (array([1.57972598e+01, 1.20274024e+00, 4.17207245e-17]), array([[ 9.35154454e-02,  9.54818342e-01,  7.07106781e-01],
       [ 5.61805577e-01,  2.83317939e-01, -7.07106781e-01],
       [ 8.21966761e-01, -8.97378394e-02, -4.99981379e-17]]))


<h3 style="color:moccasin "> => slicing </h3>

In [18]:
vector = np.array([1, 2, 3, 4, 5, 6]) 
print(vector[:])
# Select everything up to and including the third element 
print(vector[:3])
# Select everything after the third element
print(vector[3:])
# Select the last element 
print(vector[-1])
print()
# Select the first two rows and all columns of a matrix 
matrix = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])
print(matrix[:0,:]) 
print(matrix[:1,:]) 
print(matrix[:2,:1]) 
print() 
# Select all rows and the second column 
print(matrix[:,1:2])

[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6

[]
[[1 2 3]]
[[1]
 [4]]

[[2]
 [5]
 [8]]


In [19]:
matrix_a = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 2]]) 
matrix_b = np.array([[1, 3, 1], [1, 3, 1], [1, 3, 8]]) 
# Add two matrices 
adda = np.add(matrix_a, matrix_b) 
# Subtract two matrices
suba = np.subtract(matrix_a, matrix_b) 

detadda = np.linalg.det(adda)

## The inverse of a square matrix, A, is a second matrix A–1, such that: AA−1 = I
if detadda > 0:
    inve = np.linalg.inv(adda)

print(adda)
print()
print(suba)
print()
try:
    print(inve)
except:
    pass
### cause this lead to an error without initializating a "inve" variable = None at the beginning: 
# if inve is not None:
    # print(inve)
# NameError: name 'inve' is not defined

## or using builtin locals...
if 'inve' in locals():
    print(inve)

# so, using a matrix that is not singular...
x = np.arange(4, dtype=np.int8)
az = x.reshape((2,2))
print(az)
inve1 = np.linalg.inv(az)
print(inve1)

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]

[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]

[[0 1]
 [2 3]]
[[-1.5  0.5]
 [ 1.   0. ]]


<h3 style="color:moccasin "> => Generate pseudorandom values </h3>
<div style="margin-top: -9px;">
A random seed is a starting point that is used to initialize a random number generator. <br>
A random number generator is typically a deterministic algorithm that generates a sequence of seemingly random numbers based on an initial seed value.  <br>
By setting the same seed value, it is ensured that the same sequence of random numbers is generated every time the algorithm is run. <br>
</div>

In [20]:
#np.random.seed(0) 
# Generate three random floats between 0.0 and 1.0 
se1 = np.random.random(3)
print(se1)

[0.33912008 0.06808852 0.48760169]


In [21]:
# Generate three random integers between 1 and 10 
ran1 = np.random.randint(0, 11, 3) 

# Generate numbers by drawing them from a distribution: 
# Draw three numbers from a normal distribution with mean 0.0 and standard deviation of 1.0 
rano = np.random.normal(0.0, 1.0, 3) 
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0 
ralo = np.random.logistic(0.0, 1.0, 3) 
# Draw three numbers greater than or equal to 1.0 and less than 2.0 
rauni = np.random.uniform(1.0, 2.0, 3)

print(ran1)
print(rano)
print(ralo)
print(rauni)

[1 7 0]
[ 1.01569134 -2.13406147  1.14543831]
[-0.20559278  0.75872923  0.99332843]
[1.2675345  1.59155665 1.72668808]


In [23]:
vector_a = np.array([1,2,3]) 
vector_b = np.array([4,5,6]) 
# Calculate dot product 
np.dot(vector_a, vector_b)

32

In [ ]:
a1 = np.array([[0,1,2,3,4,5,6,7,8,9],
            [10,11,12,13,14,15,16,17,18,19],
            [20,21,22,23,24,25,26,27,28,29]]) # type: ignore

print(a1[1,4])
print()
print(a1[1,2])
print()
print(a1[:2]) #[0,1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18,19]]
print()
print(a1[1:3]) #[10,11,12,13,14,15,16,17,18,19],[20,21,22,23,24,25,26,27,28,29]
print()
print(a1[1,0:10:2]) #[start_index:end_index:stepsize]
print()
print(a1[1,0:-2:1]) #[start_index:end_index:stepsize]
# do not change
print()
print(a1[::])
# invert the order
print()
print(a1[::-1])
print()
print()
print()
# invert the order of items j not the external x
print()
print(a1[:, ::-1])
# invert the order of the sublists and the order of the items within each sublist
a2 = a1[:, ::-1].flatten()[::-1].reshape(a1.shape)
print()
print(a2)

14

12

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]

[10 12 14 16 18]

[10 11 12 13 14 15 16 17]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]

[[20 21 22 23 24 25 26 27 28 29]
 [10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9]]




[[ 9  8  7  6  5  4  3  2  1  0]
 [19 18 17 16 15 14 13 12 11 10]
 [29 28 27 26 25 24 23 22 21 20]]

[[20 21 22 23 24 25 26 27 28 29]
 [10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9]]


<h3 style="color:moccasin "> => Reshape </h3>

In [ ]:
arr = np.arange(10,90,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]


In [ ]:
def is_reshape_valid(arr, new_shape):
    # Compute the size of the original array
    original_size = arr.size
    # Compute the size of the reshaped array
    new_size = np.prod(new_shape)
    # Check if the sizes match
    if original_size == new_size:
        return True
    else:
        return False

ret = is_reshape_valid(arr,(2,20))
print()
print(ret)


True


In [ ]:
def get_valid_reshape_shapes_with_minus_1(arr):
    '''The -1 is a special value that can be used for one dimension of the output shape to indicate that its size should be automatically 
    calculated in the 'reshape' based on the size of the input array and the other specified dimension(s).'''
    valid_shapes = []
    size = arr.size

    for i in range(1, size + 1):
        if size % i == 0:
            valid_shapes.append((-1, i))

    for i in range(2, int(np.sqrt(size)) + 1):
        if size % i == 0:
            valid_shapes.append((-1, i, size // i))
            valid_shapes.append((-1, size // i, i))

    return valid_shapes

retta = get_valid_reshape_shapes_with_minus_1(arr)
print()
print(retta)


[(-1, 1), (-1, 2), (-1, 4), (-1, 5), (-1, 8), (-1, 10), (-1, 20), (-1, 40), (-1, 2, 20), (-1, 20, 2), (-1, 4, 10), (-1, 10, 4), (-1, 5, 8), (-1, 8, 5)]


In [ ]:
def get_valid_reshape_shapes(arr):
    valid_shapes = []
    size = arr.size

    for i in range(1, size + 1):
        if size % i == 0:
            valid_shapes.append((i, size // i))

    return valid_shapes

rere = get_valid_reshape_shapes(arr)
print()
# prova_res = arr.reshape(2,20)
# prova_res = arr.reshape(-1, 2, 20)
print(rere)
print()
print()
#print(prova_res)


[(1, 40), (2, 20), (4, 10), (5, 8), (8, 5), (10, 4), (20, 2), (40, 1)]




reshape(-1) #the same as flatten

In [ ]:
aaa = arr.reshape(-1)
aab = arr.flatten()
print(aaa)
print()
print(aab)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88]


<h3 style="color:moccasin "> => Merge </h3>

In [ ]:
abc = [1,2,3,4,5]
cba = [5,4,3,2,1]
tot = abc + cba
print(f"tot is {tot}")
print()

o = np.ones((5,5))
z = np.zeros((3,3))
z[1,1]=9
print(o)
print()
print(z)
print()
print(o[1:-1,1:-1])
print()
o[1:-1,1:-1] = z
print(o)

tot is [1, 2, 3, 4, 5, 5, 4, 3, 2, 1]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
#after = before.reshape((2,3)) #mismatch!! 
after = before.reshape((2,2,2))
print(after)
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
v3 = np.vstack([v1,v2,v2]) #[[1 2 3 4],[5 6 7 8],[5 6 7 8]]
print()
print(v3)
v4 = np.hstack([v1,v2]) #[1 2 3 4 5 6 7 8]
print()
print(v4)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]

[1 2 3 4 5 6 7 8]


In [ ]:
# v3 >> [[1 2 3 4],[5 6 7 8],[5 6 7 8]]
resp0 = np.any(v3 > 3, axis=0) 
resp1 = np.any(v3 < 3, axis=1) 

print(resp0)
print(resp1)

### axis=0 specifies that the operation should be performed along the first axis (i.e., the rows) of the input array. 
# returns a boolean array indicating whether there is any element greater than 3 in each column of v3.

### axis=1 specifies that the operation should be performed along the second axis (i.e., the columns) of the input array.
# returns a boolean array indicating whether there is any element less than 3 in each row of v3.


[ True  True  True  True]
[ True False False]


In [ ]:
xy = [(i,j) for i in np.linspace(1,4,4) for j in np.linspace(0,2,3)]

print(xy)

#to create two 2D arrays X and Y with the same shape, 
# where each element in X and Y corresponds to a point in a 2D plane. 
# slice => values ranging from -5 to 5.1 (inclusive) in steps of 0.5.
X,Y = np.mgrid[-5:5.1:0.5, -5:5.1:0.5]
xxy = np.vstack((X.flatten(), Y.flatten())).T
xy = np.mgrid[-5:5.1:0.5, -5:5.1:0.5].reshape(2, -1).T

print()
print(X)
print()
print(Y)
print()
print(xxy)
print()
print(xy)


[(1.0, 0.0), (1.0, 1.0), (1.0, 2.0), (2.0, 0.0), (2.0, 1.0), (2.0, 2.0), (3.0, 0.0), (3.0, 1.0), (3.0, 2.0), (4.0, 0.0), (4.0, 1.0), (4.0, 2.0)]

[[-5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.  -5.
  -5.  -5.  -5.  -5.  -5.  -5.  -5. ]
 [-4.5 -4.5 -4.5 -4.5 -4.5 -4.5 -4.5 -4.5 -4.5 -4.5 -4.5 -4.5 -4.5 -4.5
  -4.5 -4.5 -4.5 -4.5 -4.5 -4.5 -4.5]
 [-4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.  -4.
  -4.  -4.  -4.  -4.  -4.  -4.  -4. ]
 [-3.5 -3.5 -3.5 -3.5 -3.5 -3.5 -3.5 -3.5 -3.5 -3.5 -3.5 -3.5 -3.5 -3.5
  -3.5 -3.5 -3.5 -3.5 -3.5 -3.5 -3.5]
 [-3.  -3.  -3.  -3.  -3.  -3.  -3.  -3.  -3.  -3.  -3.  -3.  -3.  -3.
  -3.  -3.  -3.  -3.  -3.  -3.  -3. ]
 [-2.5 -2.5 -2.5 -2.5 -2.5 -2.5 -2.5 -2.5 -2.5 -2.5 -2.5 -2.5 -2.5 -2.5
  -2.5 -2.5 -2.5 -2.5 -2.5 -2.5 -2.5]
 [-2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.  -2.
  -2.  -2.  -2.  -2.  -2.  -2.  -2. ]
 [-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5
  -1.5 -1.5 -1.5

<h3 style="color:moccasin "> => Create rows from matrix </h3>

In [ ]:
matrix = np.array([[0, 0], [0, 1], [3, 0]]) 
# Create compressed sparse row (CSR) matrix 
ma_spa = sc.sparse.csr_matrix(matrix)
print(ma_spa)
print()
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]]) 
# Create compressed sparse row (CSR) matrix 
matrix_large_sparse = sc.sparse.csr_matrix(matrix_large) 
# View larger sparse matrix print(matrix_large_sparse) (1, 1) 1 (2, 0) 3
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3

  (1, 1)	1
  (2, 0)	3


<h3 style="color:moccasin "> => Iterate </h3>

In [ ]:
arrat = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

for _ in arrat:
    print(_)
print("or:")
for i in range(len(arrat)):
    for j in range(len(arrat[i])):
        print(arrat[i][j])
print()
print()
###################################################################################
for x in np.nditer(arrat):
    print(x, end='')
print()
for x in np.nditer(arrat,flags=['buffered'], op_dtypes=['S']):
    print(x)
print()
for idx, x in np.ndenumerate(arrat):
    print(idx, x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
or:
[1 2 3]
[4 5 6]
[7 8 9]


123456789
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9


In [ ]:
array_casual = [1,2,'ciao',None]
if None in array_casual:
    print('ca')

listone = [i for i in range(len(array_casual)) if array_casual[i] == None]
# or 
listone1 = np.where(np.array(array_casual) == None)[0].tolist()
print(listone)
print(listone1)


ca
[3]
[3]
